my_string = input('Введите название предмета: ')
print(len(my_string))
print('Введите название предмета: '.upper())
print('Введите название предмета: '.upper().lower())
print('Введите название предмета: '.replace(' ',''))
print('Первый символ строки: ', my_string[0])
print('Последний символ строки: ', my_string[-1])